[mypy]
python_version = 3.12
files = iara/

disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
warn_unused_ignores = true
warn_unreachable = true

# Third-party libraries without stubs
ignore_missing_imports = true
